version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: token_bridge
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: token-bridge-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: token_bridge
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: mysecretkey
      SEPOLIA_RPC_URL: https://eth-sepolia.alchemyapi.io/v2/your-api-key
      BSC_TESTNET_RPC_URL: https://bsc-testnet.nodereal.io/v1/your-api-key
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: